export const INITIAL_PIE_CHART_DATA = [
  {
    x: 1,
    y: 350,
    size: 35,
    label: "Jan",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 2,
    y: 200,
    size: 20,
    label: "Feb",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 3,
    y: 100,
    size: 10,
    label: "Mar",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 4,
    y: 189,
    size: 18,
    label: "Apr",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 5,
    y: 123,
    size: 12,
    label: "May",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 6,
    y: 321,
    size: 32,
    label: "June",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 7,
    y: 222,
    size: 22,
    label: "July",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 8,
    y: 265,
    size: 26,
    label: "Aug",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 9,
    y: 176,
    size: 17,
    label: "Sept",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 10,
    y: 175,
    size: 17,
    label: "Oct",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 11,
    y: 185,
    size: 18,
    label: "Nov",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
  {
    x: 12,
    y: 88,
    size: 88,
    label: "Dec",
    pie: [
      { label: "electricity bills", x: "Lions", y: 50 },
      { label: "house bill", x: "Tigers", y: 40 },
      { label: "super market", x: "Bears", y: 15 },
      { label: "water bill", x: "Bears", y: 15 },
      { label: "clothing", x: "Bears", y: 15 },
      { label: "night out", x: "Bears", y: 10 },
    ],
  },
];
const example = [
  {
    label: "Dec",
    pie: [
      { label: "Lions", x: "Lions", y: 3 },
      { label: "Tigers", x: "Tigers", y: 9 },
      { label: "Bears", x: "Bears", y: 7 },
    ],
    size: 88,
    x: 12,
    y: 88,
  },
];

export const INITIAL_MONTHLY_DATA = [
  { x: 1, y: 350, size: 35, label: `Jan ${350}$` },
  { x: 2, y: 200, size: 20, label: `Feb ${200}$` },
  { x: 3, y: 100, size: 10, label: `Mar ${100}$` },
  { x: 4, y: 189, size: 18, label: `Apr ${189}$` },
  { x: 5, y: 123, size: 12, label: `May ${123}$` },
  { x: 6, y: 321, size: 32, label: `June ${321}$` },
  { x: 7, y: 222, size: 22, label: `July ${222}$` },
  { x: 8, y: 265, size: 26, label: `Aug ${265}$` },
  { x: 9, y: 176, size: 17, label: `Sept ${176}$` },
  { x: 10, y: 175, size: 17, label: `Oct ${175}$` },
  { x: 11, y: 185, size: 18, label: `Nov ${185}$` },
  { x: 12, y: 88, size: 88, label: `Dec ${88}$` },
];

export const INITIAL_CHARGE_STATE = { type: "", month: 1, amount: 0 };
