export const lectors = [
  {
    name: "brynn",
    avatar: "https://uifaces.co/our-content/donated/1H_7AxP0.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "thot leader",
    avatar:
      "https://images.pexels.com/photos/598745/pexels-photo-598745.jpeg?crop=faces&fit=crop&h=200&w=200&auto=compress&cs=tinysrgb",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "jsa",
    avatar: "https://uifaces.co/our-content/donated/bUkmHPKs.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "talhaconcepts",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "andy vitale",
    avatar: "https://uifaces.co/our-content/donated/NY9hnAbp.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "katy friedson",
    avatar:
      "https://images-na.ssl-images-amazon.com/images/M/MV5BMTgxMTc1MTYzM15BMl5BanBnXkFtZTgwNzI5NjMwOTE@._V1_UY256_CR16,0,172,256_AL_.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "elsa wilinction",
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "forssake",
    avatar: "https://randomuser.me/api/portraits/women/29.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "andy vitale jr",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
  {
    name: "Laly Polyrdon",
    avatar: "https://randomuser.me/api/portraits/men/98.jpg",
    type: "a",
    desk: "AB32",
    telephone: "2102323232",
    email: "example@email.com",
  },
];
